JWTKey: test

spring:
  application.name: member

  profiles:
    active: dev

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka.client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://${url}:8761/eureka