spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/member
    username: root
    password: 1234

  redis:
    host: redis
    port: 6379

eureka.client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://eureka:8761/eureka