spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/website?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${password}

  redis:
    host: localhost
    port: 6379

eureka.client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: http://${url}:8761/eureka